# Daten laden

---

In [1]:
import pandas as pd

import warnings
warnings.filterwarnings("ignore", category=FutureWarning)

In [2]:
df = pd.read_csv("data/avocado-updated-2020.csv") # Patrick 07.10.2024: Daten im colab hochgeladen
df

,date,average_price,total_volume,4046,4225,4770,total_bags,small_bags,large_bags,xlarge_bags,type,year,geography
0,2015-01-04,1.22,40873.28,2819.50,28287.42,49.90,9716.46,9186.93,529.53,0.00,conventional,2015,Albany
1,2015-01-04,1.79,1373.95,57.42,153.88,0.00,1162.65,1162.65,0.00,0.00,organic,2015,Albany
2,2015-01-04,1.00,435021.49,364302.39,23821.16,82.15,46815.79,16707.15,30108.64,0.00,conventional,2015,Atlanta
3,2015-01-04,1.76,3846.69,1500.15,938.35,0.00,1408.19,1071.35,336.84,0.00,organic,2015,Atlanta
4,2015-01-04,1.08,788025.06,53987.31,552906.04,39995.03,141136.68,137146.07,3990.61,0.00,conventional,2015,Baltimore/Washington
...,...,...,...,...,...,...,...,...,...,...,...,...,...
33040,2020-11-29,1.47,1583056.27,67544.48,97996.46,2617.17,1414878.10,906711.52,480191.83,27974.75,organic,2020,Total U.S.
33041,2020-11-29,0.91,5811114.22,1352877.53,589061.83,19741.90,3790665.29,2197611.02,1531530.14,61524.13,conventional,2020,West
33042,2020-11-29,1.48,289961.27,13273.75,19341.09,636.51,256709.92,122606.21,134103.71,0.00,organic,2020,West
33043,2020-11-29,0.67,822818.75,234688.01,80205.15,10543.63,497381.96,285764.11,210808.02,809.83,conventional,2020,West Tex/New Mexico
33044,2020-11-29,1.35,24106.58,1236.96,617.80,1564.98,20686.84,17824.52,2862.32,0.00,organic,2020,West Tex/New Mexico

In [3]:
# Prüfung, ob der Datenrahmen Nullwerte enthält
df.isnull().values.any()

False

In [4]:
df.isnull().sum()

date             0
average_price    0
total_volume     0
4046             0
4225             0
4770             0
total_bags       0
small_bags       0
large_bags       0
xlarge_bags      0
type             0
year             0
geography        0
dtype: int64

# Daten verstehen


---

In [5]:
df.columns

Index(['date', 'average_price', 'total_volume', '4046', '4225', '4770',
       'total_bags', 'small_bags', 'large_bags', 'xlarge_bags', 'type', 'year',
       'geography'],
      dtype='object')

In [6]:
df.shape

(33045, 13)

In [7]:
df.dtypes

date              object
average_price    float64
total_volume     float64
4046             float64
4225             float64
4770             float64
total_bags       float64
small_bags       float64
large_bags       float64
xlarge_bags      float64
type              object
year               int64
geography         object
dtype: object

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33045 entries, 0 to 33044
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           33045 non-null  object
 1   average_price  33045 non-null  float64
 2   total_volume   33045 non-null  float64
 3   4046           33045 non-null  float64
 4   4225           33045 non-null  float64
 5   4770           33045 non-null  float64
 6   total_bags     33045 non-null  float64
 7   small_bags     33045 non-null  float64
 8   large_bags     33045 non-null  float64
 9   xlarge_bags    33045 non-null  float64
 10  type           33045 non-null  object
 11  year           33045 non-null  int64
 12  geography      33045 non-null  object
dtypes: float64(9), int64(1), object(3)
memory usage: 3.3+ MB

In [9]:
df.describe()

,average_price,total_volume,4046,4225,4770,total_bags,small_bags,large_bags,xlarge_bags,year
count,33045.000000,3.304500e+04,3.304500e+04,3.304500e+04,3.304500e+04,3.304500e+04,3.304500e+04,3.304500e+04,3.304500e+04,33045.000000
mean,1.379941,9.683997e+05,3.023914e+05,2.797693e+05,2.148255e+04,3.646735e+05,2.501980e+05,1.067329e+05,7.742585e+03,2017.460887
std,0.378972,3.934533e+06,1.301026e+06,1.151052e+06,1.001607e+05,1.564004e+06,1.037734e+06,5.167226e+05,4.819803e+04,1.699747
min,0.440000,8.456000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,2015.000000
25%,1.100000,1.511895e+04,7.673100e+02,2.712470e+03,0.000000e+00,9.121860e+03,6.478630e+03,4.662900e+02,0.000000e+00,2016.000000
50%,1.350000,1.291170e+05,1.099477e+04,2.343600e+04,1.780900e+02,5.322224e+04,3.687699e+04,6.375860e+03,0.000000e+00,2017.000000
75%,1.620000,5.058285e+05,1.190219e+05,1.352389e+05,5.096530e+03,1.744314e+05,1.206624e+05,4.041723e+04,8.044400e+02,2019.000000
max,3.250000,6.371614e+07,2.274362e+07,2.047057e+07,2.546439e+06,3.168919e+07,2.055041e+07,1.332760e+07,1.403184e+06,2020.000000

Brian

|   Spalte      | Typ     | Beschreibung                                    |
|---------------|---------|-------------------------------------------------|
| date          | object  |                                                 |
| average_price | float64 |                                                 |
| total_volume  | float64 |                                                 |
| 4046          | float64 | kleine/mittlere Bio-Hass-Avocados               |
| 4225          | float64 | große Hass-Avocados aus nicht                   |   
|               |         | biologischem Anbau                              |
| 4770          | float64 | nicht-biologische extra große Hass-Avocados     |
| total_bags    | float64 |                                                 |
| small_bags    | float64 |                                                 |
| large_bags    | float64 |                                                 |
| xlarge_bags   | float64 |                                                 |
| type          | object  |                                                 |
| year          | int64   |                                                 |
| geography     | object  |                                                 |


1.	Überblick über die Daten
  * 1.1.  4046: organic small/medium Hass Avocados (~3-5 oz)
  * 1.2.  4225: non-organic large Hass Avocados (~8-10 oz)
  * 1.2.  4770: non-organic extra large Hass Avocados (~10-15 oz)

* https://www.kaggle.com/code/shaniquehines/avocados-case-study

In [10]:
# Spalte 'date' in Datumsformat umwandeln (falls sie als String vorliegt)
df['date'] = pd.to_datetime(df['date'])

# Sortieren nach Datum (optional, um sicherzustellen, dass die Daten chronologisch sind)
df = df.sort_values(by='date').reset_index(drop=True)

# Berechnen des frühesten Datums im Datensatz
min_date = df['date'].min()

# Berechnen der Anzahl der Tage seit dem frühesten Datum
df['date_number'] = (df['date'] - min_date).dt.days

# Die Spalte 'date_number' an den Anfang verschieben
cols = ['date_number'] + [col for col in df.columns if col != 'date_number']  # Neue Reihenfolge der Spalten
df = df[cols]

# Encoder

## Date/Lag/Avr-Encoder

**Problemstellung:**
Zeitvariablen wie Monate oder Tage der Woche haben eine zyklische Natur (z.B. Januar folgt auf Dezember). Klassische maschinelle Lernmodelle wie Support Vector Regression (SVR) erkennen diese zyklischen Muster jedoch nicht automatisch. Zudem reichen einfache Zeitreihen nicht aus, um saisonale Schwankungen oder zeitliche Abhängigkeiten korrekt abzubilden.

**Lösung:**
Um die zyklische Struktur der Zeit und historische Preisinformationen korrekt zu berücksichtigen, wurden folgende Spalten erstellt:

*Zyklische Kodierung (Monat)*: Durch Umwandlung der Monate in Sinus- und Cosinus-Werte wird die zyklische Natur korrekt erfasst. Dies sorgt dafür, dass Januar und Dezember als benachbart angesehen werden.

*Lag-Features (Verzögerungsmerkmale)*: Verzögerungsmerkmale (z.B. Preise vor einer Woche oder einem Monat) helfen dem Modell, saisonale oder zeitliche Abhängigkeiten besser zu berücksichtigen.

*Gleitende Durchschnitte*: Kurzfristige Trends und saisonale Muster werden durch gleitende Durchschnitte geglättet, um das Modell robuster gegen kurzfristige Schwankungen zu machen.

Diese Features verbessern die Fähigkeit des Modells, zeitliche Abhängigkeiten und saisonale Muster korrekt zu erfassen.

In [11]:
# Patrick DateEncoder für Monate
import numpy as np

# -------------------------------
# Extrahiere Zeitkomponenten
# -------------------------------
# Monat aus der "date"-Spalte extrahieren
df['month'] = df['date'].dt.month   # Monat extrahieren

# -------------------------------
# Zyklische Kodierung
# -------------------------------
# Monat zyklisch mit sin und cos kodieren, um die zyklische Natur (Januar -> Dezember) zu berücksichtigen
df['month_sin'] = np.sin(2 * np.pi * df['month'] / 12)
df['month_cos'] = np.cos(2 * np.pi * df['month'] / 12)

# -------------------------------
# Lag-Features (Verzögerungsmerkmale)
# -------------------------------
# Erstelle Verzögerungsmerkmale für den durchschnittlichen Preis
# Preis vor einer Woche und vor einem Monat
df['lag_7'] = df['average_price'].shift(7)   # Preis vor einer Woche
df['lag_30'] = df['average_price'].shift(30) # Preis vor einem Monat

# -------------------------------
# Gleitende Durchschnitte
# -------------------------------
# Gleitender Durchschnitt des Preises der letzten 7 Tage (Fenstergröße 14 für Glättung)
#df['moving_avg_7'] = df['average_price'].rolling(window=14).mean()

# Gleitender Durchschnitt des Preises der letzten 30 Tage
df['moving_avg_30'] = df['average_price'].rolling(window=30).mean()

# Auffüllen der NaN-Werte in den Lag- und Moving-Average-Spalten mit dem Wert der 'average_price' in der gleichen Zeile

# Fülle Lag-Features mit dem Wert der 'average_price' in der gleichen Zeile
df['lag_7'].fillna(df['average_price'], inplace=True)
df['lag_30'].fillna(df['average_price'], inplace=True)

# Fülle gleitende Durchschnitte mit dem Wert der 'average_price' in der gleichen Zeile
#df['moving_avg_7'].fillna(df['average_price'], inplace=True)
df['moving_avg_30'].fillna(df['average_price'], inplace=True)

# Entfernen der angegebenen Spalten
df = df.drop(columns=['month'])

## Harvest Endcoder

In [12]:
# Mark / Mathieu
# Funktion zur Kodierung je nach Monat
def encode_month(date):
    month = date.month
    if 1 <= month <= 3:
        return 1
    elif 4 <= month <= 5:
        return 0.5
    else:
        return 0

# Kodierungsspalte hinzufügen
df['harvest_indicator'] = df['date'].apply(encode_month)

In [13]:
df.tail()

,date_number,date,average_price,total_volume,4046,4225,4770,total_bags,small_bags,large_bags,xlarge_bags,type,year,geography,month_sin,month_cos,lag_7,lag_30,moving_avg_30,harvest_indicator
33040,2156,2020-11-29,1.20,5270.83,5.86,499.77,0.00,4765.20,4765.20,0.00,0.00,organic,2020,Grand Rapids,-0.5,0.866025,0.66,1.52,1.066000,0.0
33041,2156,2020-11-29,1.21,156868.20,17780.46,43514.67,44314.73,51258.34,39468.06,5111.72,6678.56,conventional,2020,Grand Rapids,-0.5,0.866025,1.87,0.73,1.082000,0.0
33042,2156,2020-11-29,1.36,19723.34,252.24,1364.20,0.00,18106.90,3864.71,14242.19,0.00,organic,2020,Detroit,-0.5,0.866025,1.19,1.45,1.079000,0.0
33043,2156,2020-11-29,0.78,200284.09,48129.95,37637.47,5118.56,109398.11,100336.24,3084.27,5977.60,conventional,2020,Indianapolis,-0.5,0.866025,1.26,0.91,1.074667,0.0
33044,2156,2020-11-29,1.35,24106.58,1236.96,617.80,1564.98,20686.84,17824.52,2862.32,0.00,organic,2020,West Tex/New Mexico,-0.5,0.866025,0.95,0.67,1.097333,0.0

## LabelEncoder Geography

In [14]:
from sklearn.preprocessing import LabelEncoder

lb = LabelEncoder()
df['type'] = lb.fit_transform(df['type'])

# Encoder:
# organic = 1
# conventional = 0

In [15]:
df.tail()

,date_number,date,average_price,total_volume,4046,4225,4770,total_bags,small_bags,large_bags,xlarge_bags,type,year,geography,month_sin,month_cos,lag_7,lag_30,moving_avg_30,harvest_indicator
33040,2156,2020-11-29,1.20,5270.83,5.86,499.77,0.00,4765.20,4765.20,0.00,0.00,1,2020,Grand Rapids,-0.5,0.866025,0.66,1.52,1.066000,0.0
33041,2156,2020-11-29,1.21,156868.20,17780.46,43514.67,44314.73,51258.34,39468.06,5111.72,6678.56,0,2020,Grand Rapids,-0.5,0.866025,1.87,0.73,1.082000,0.0
33042,2156,2020-11-29,1.36,19723.34,252.24,1364.20,0.00,18106.90,3864.71,14242.19,0.00,1,2020,Detroit,-0.5,0.866025,1.19,1.45,1.079000,0.0
33043,2156,2020-11-29,0.78,200284.09,48129.95,37637.47,5118.56,109398.11,100336.24,3084.27,5977.60,0,2020,Indianapolis,-0.5,0.866025,1.26,0.91,1.074667,0.0
33044,2156,2020-11-29,1.35,24106.58,1236.96,617.80,1564.98,20686.84,17824.52,2862.32,0.00,1,2020,West Tex/New Mexico,-0.5,0.866025,0.95,0.67,1.097333,0.0

## GeoDistanceEncoder

In [16]:
# Patrick LabelEncoder für geography


# Importieren der notwendigen Bibliotheken
from sklearn.preprocessing import LabelEncoder

# Initialisierung des LabelEncoders für die 'geography'-Spalte
geo_encoder = LabelEncoder()
# Anwenden des Encoders auf die 'geography'-Spalte
df['geography_encoded'] = geo_encoder.fit_transform(df['geography'])

# Anzeigen der ersten Zeilen des Datensatzes, um die Ergebnisse zu überprüfen
print(df[['geography', 'geography_encoded']].head())

# Optional: Speichern des modifizierten Datensatzes in eine neue CSV-Datei
# avocado_data.to_csv("data/avocado_encoded.csv", index=False)

            geography  geography_encoded
0              Albany                  0
1             Roanoke                 39
2    Richmond/Norfolk                 38
3    Richmond/Norfolk                 38
4  Raleigh/Greensboro                 37

In [17]:
# Patrick GeoDistanceEncoder für geography

# Importieren der notwendigen Bibliotheken
from geopy.distance import geodesic

# Definieren der Städte mit ihren Koordinaten
static_coordinates = [
    ('Albany', 42.6526, -73.7562),
    ('Atlanta', 33.749, -84.388),
    ('Baltimore/Washington', 39.2904, -76.6122),
    ('Boise', 43.615, -116.2023),
    ('Boston', 42.3601, -71.0589),
    ('Buffalo/Rochester', 43.1566, -77.6088),
    ('California', 36.7783, -119.4179),
    ('Charlotte', 35.2271, -80.8431),
    ('Chicago', 41.8781, -87.6298),
    ('Cincinnati/Dayton', 39.1031, -84.512),
    ('Columbus', 39.9612, -82.9988),
    ('Dallas/Ft. Worth', 32.7767, -96.797),
    ('Denver', 39.7392, -104.9903),
    ('Detroit', 42.3314, -83.0458),
    ('Grand Rapids', 42.9634, -85.6681),
    ('Great Lakes', 45.0, -84.0),
    ('Harrisburg/Scranton', 40.2732, -76.8867),
    ('Hartford/Springfield', 41.7627, -72.6743),
    ('Houston', 29.7604, -95.3698),
    ('Indianapolis', 39.7684, -86.1581),
    ('Jacksonville', 30.3322, -81.6557),
    ('Las Vegas', 36.1699, -115.1398),
    ('Los Angeles', 34.0522, -118.2437),
    ('Louisville', 38.2527, -85.7585),
    ('Miami/Ft. Lauderdale', 25.7617, -80.1918),
    ('Midsouth', 35.1495, -90.0489),
    ('Nashville', 36.1627, -86.7816),
    ('New Orleans/Mobile', 29.9511, -90.0715),
    ('New York', 40.7128, -74.006),
    ('Northeast', 41.5, -75.0),
    ('Northern New England', 44.0, -71.5),
    ('Orlando', 28.5383, -81.3792),
    ('Philadelphia', 39.9526, -75.1652),
    ('Phoenix/Tucson', 33.4484, -112.074),
    ('Pittsburgh', 40.4406, -79.9959),
    ('Plains', 39.0119, -98.4842),
    ('Portland', 45.5152, -122.6784),
    ('Raleigh/Greensboro', 35.7796, -78.6382),
    ('Richmond/Norfolk', 37.5407, -77.436),
    ('Roanoke', 37.2709, -79.9414),
    ('Sacramento', 38.5816, -121.4944),
    ('San Diego', 32.7157, -117.1611),
    ('San Francisco', 37.7749, -122.4194),
    ('Seattle', 47.6062, -122.3321),
    ('South Carolina', 33.8361, -81.1637),
    ('South Central', 34.7465, -92.2896),
    ('Southeast', 32.3182, -86.9023),
    ('Spokane', 47.6588, -117.426),
    ('St. Louis', 38.627, -90.1994),
    ('Syracuse', 43.0481, -76.1474),
    ('Tampa', 27.9506, -82.4572),
    ('Total U.S.', 39.8283, -98.5795),
    ('West', 39.1178, -120.013),
    ('West Tex/New Mexico', 31.9686, -99.9018)
]


class GeoDistanceEncoder:
    def __init__(self, city_coordinates, reference_points):
        """
        Initialisiert den GeoDistanceEncoder mit den Städten und den Referenzpunkten.

        :param city_coordinates: Dictionary mit Städtenamen und deren (Latitude, Longitude)-Koordinaten
        :param reference_points: Dictionary mit Referenzpunkten und deren (Latitude, Longitude)-Koordinaten
        """
        self.city_coordinates = city_coordinates
        self.reference_points = reference_points

    def fit(self, X, y=None):
        # fit ist nicht notwendig, wird aber für Kompatibilität bereitgestellt.
        return self

    def transform(self, X):
        """
        Berechnet die geografischen Distanzen zu den Referenzpunkten. Falls die Spalten 'latitude' und 'longitude'
        nicht im Datensatz vorhanden sind, werden sie anhand der Stadtzuordnung berechnet.

        :param X: DataFrame mit der Spalte 'geography' (Städte) und optional 'latitude' und 'longitude'
        :return: DataFrame mit den berechneten Distanzen zu den Referenzpunkten
        """
        # Überprüfen, ob die Spalten 'latitude' und 'longitude' bereits vorhanden sind
        if 'latitude' not in X.columns or 'longitude' not in X.columns:
            # Falls die Spalten nicht existieren, die Koordinaten der Städte hinzufügen
            X['latitude'] = X['geography'].map(lambda x: self.city_coordinates.get(x, (None, None))[0])
            X['longitude'] = X['geography'].map(lambda x: self.city_coordinates.get(x, (None, None))[1])

        # Entfernen von Zeilen ohne gültige Koordinaten
        X = X.dropna(subset=['latitude', 'longitude'])

        # Berechnen der Entfernungen zu den Referenzpunkten
        for name, coords in self.reference_points.items():
            X[f'dist_to_{name}'] = X.apply(lambda row: geodesic((row['latitude'], row['longitude']), coords).kilometers, axis=1)

        return X

    def fit_transform(self, X, y=None):
        """
        Führt fit und transform direkt hintereinander aus.

        :param X: DataFrame mit der Spalte 'geography' (Städte) und optional 'latitude' und 'longitude'
        :return: DataFrame mit den berechneten Distanzen zu den Referenzpunkten
        """
        return self.fit(X).transform(X)

# Umwandeln der Liste in ein Dictionary für den Encoder
city_coordinates = {city: (lat, lon) for city, lat, lon in static_coordinates}

# Referenzpunkte (Kalifornien und Mexiko)
reference_points = {
    'california': (36.7783, -119.4179),
    'mexico': (23.6345, -102.5528)
}

# Anwendung des GeoDistanceEncoders
encoder = GeoDistanceEncoder(city_coordinates, reference_points)
df = encoder.fit_transform(df)

# Überprüfen der ersten Zeilen des Datensatzes
print(df[['geography', 'latitude', 'longitude', 'dist_to_california', 'dist_to_mexico']].head())

            geography  latitude  longitude  dist_to_california  dist_to_mexico
0              Albany   42.6526   -73.7562         3920.853266     3386.636000
1             Roanoke   37.2709   -79.9414         3487.216026     2634.449547
2    Richmond/Norfolk   37.5407   -77.4360         3698.524169     2845.554511
3    Richmond/Norfolk   37.5407   -77.4360         3698.524169     2845.554511
4  Raleigh/Greensboro   35.7796   -78.6382         3637.489516     2666.220116

## East/West Aufteilung

In [18]:
# Aufteilung in Westküste und Ostküste
def classify_region(dataset):
    west_coast_regions = ['California', 'Portland', 'Seattle', 'Los Angeles', 'San Francisco']
    east_coast_regions = ['New York', 'Boston', 'Miami', 'Philadelphia', 'Baltimore/Washington',
                          'Atlanta', 'Tampa', 'Orlando', 'Hartford/Springfield', 'Raleigh/Greensboro', 'Richmond/Norfolk']
    #closer_east_coast = ['Albany','Buffalo/Rochester','Charlotte','Chicago','Cincinnati/Dayton','Columbus',
    #                     'Dallas/Ft. Worth','Detroit','Grand Rapids','Great Lakes','Harrisburg/Scranton','Houston',
    #                     'Indianapolis','Jacksonville','Louisville','Midsouth','Nashville','New Orleans/Mobile',
    #                  'Northeast','Northern New England','Pittsburgh','Plains','Roanoke','South Carolina',
    #                     'South Central','Southeast','St. Louis','Syracuse','Total U.S']
    #closer_west_coast = ['Boise','Las Vegas','Denver','Phoenix/Tucson','Sacramento','San Diego','Spokane','West Tex/New Mexico','West']

    #merged_east_coast = list(set(east_coast_regions + closer_east_coast))
    #merged_west_coast = list(set(west_coast_regions + closer_west_coast))

    dataset['region'] = dataset['geography'].apply(
    lambda x: 0 if any(west in x for west in west_coast_regions) else
              (1 if any(east in x for east in east_coast_regions) else None)
  )
    return dataset

df = classify_region(df)
df.head(20)
df = df.dropna(subset=['region'])
df

,date_number,date,average_price,total_volume,4046,4225,4770,total_bags,small_bags,large_bags,...,lag_7,lag_30,moving_avg_30,harvest_indicator,geography_encoded,latitude,longitude,dist_to_california,dist_to_mexico,region
2,0,2015-01-04,1.54,4212.16,238.48,1678.83,372.55,1922.30,1570.28,352.02,...,1.54,1.54,1.540000,1.0,38,37.5407,-77.4360,3698.524169,2845.554511,1.0
3,0,2015-01-04,1.13,182697.97,56293.75,80396.09,9762.41,36245.72,31778.36,4467.36,...,1.13,1.13,1.130000,1.0,38,37.5407,-77.4360,3698.524169,2845.554511,1.0
4,0,2015-01-04,2.01,3397.00,58.22,1493.90,772.21,1072.67,993.94,78.73,...,2.01,2.01,2.010000,1.0,37,35.7796,-78.6382,3637.489516,2666.220116,1.0
5,0,2015-01-04,1.20,221086.46,53316.16,72178.46,39928.01,55663.83,44040.64,11623.19,...,1.20,1.20,1.200000,1.0,37,35.7796,-78.6382,3637.489516,2666.220116,1.0
6,0,2015-01-04,1.28,32927.82,17580.96,11685.08,3.15,3658.63,613.33,3045.30,...,1.28,1.28,1.280000,1.0,36,45.5152,-122.6784,1007.919818,3031.428771,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33021,2156,2020-11-29,0.68,981184.37,476833.70,32798.09,85.73,471455.80,418334.06,52360.63,...,0.67,1.31,1.168333,0.0,24,25.7617,-80.1918,3899.278418,2272.327564,1.0
33024,2156,2020-11-29,1.74,135939.83,6283.66,1658.88,4.65,127992.64,63390.70,64601.94,...,0.94,1.62,1.166667,0.0,22,34.0522,-118.2437,320.698548,1913.632577,0.0
33025,2156,2020-11-29,1.06,2490232.13,848920.05,47467.30,77620.80,1516223.98,989779.93,420508.95,...,1.17,0.95,1.170333,0.0,22,34.0522,-118.2437,320.698548,1913.632577,0.0
33034,2156,2020-11-29,1.87,13556.49,217.80,5381.28,0.00,7957.41,7945.32,12.09,...,0.80,1.77,1.095667,0.0,17,41.7627,-72.6743,4021.631031,3419.193881,1.0
33035,2156,2020-11-29,1.19,325928.47,8496.29,238481.65,230.96,78719.57,65676.32,9996.58,...,1.06,1.27,1.093000,0.0,17,41.7627,-72.6743,4021.631031,3419.193881,1.0

## OneHot Encoder Geography

In [19]:
# Importieren der notwendigen Bibliotheken
#import pandas as pd
#from sklearn.preprocessing import OneHotEncoder

# Initialisierung des OneHotEncoders
#onehot_encoder = OneHotEncoder(sparse_output=False, handle_unknown='ignore')

# Anwenden des OneHotEncoders auf die 'geography'-Spalte
#encoded_data = onehot_encoder.fit_transform(df[['geography']])

# Erstellen eines DataFrames aus den OneHotEncoded-Daten
#encoded_df = pd.DataFrame(encoded_data, columns=onehot_encoder.get_feature_names_out(['geography']))

# Zusammenführen der kodierten Daten mit dem Original-DataFrame
#df = pd.concat([df, encoded_df], axis=1)

# Ausgabe des Ergebnisses
#print(df)


def onehot_encode(df, column):
  # Make a copy of the origianl DataFrame
  df = df.copy()

  # Create dummy variables (one-hot encoding)
  dummies = pd.get_dummies(df[column])

  # Convert dummy columns to integers (0 and 1)
  dummies = dummies.astype(int)

  # Concatenate the dummy variables to the original DataFrame
  df = pd.concat([df, dummies], axis=1)

  # Drop the original column from the DataFrame
  df.drop(column, axis =1, inplace = True)
  return df

In [20]:
df = onehot_encode(df, 'geography')

In [21]:
# Überprüfung NaN-Werte

df.isnull().sum()

date_number             0
date                    0
average_price           0
total_volume            0
4046                    0
4225                    0
4770                    0
total_bags              0
small_bags              0
large_bags              0
xlarge_bags             0
type                    0
year                    0
month_sin               0
month_cos               0
lag_7                   0
lag_30                  0
moving_avg_30           0
harvest_indicator       0
geography_encoded       0
latitude                0
longitude               0
dist_to_california      0
dist_to_mexico          0
region                  0
Atlanta                 0
Baltimore/Washington    0
Boston                  0
California              0
Hartford/Springfield    0
Los Angeles             0
Miami/Ft. Lauderdale    0
New York                0
Orlando                 0
Philadelphia            0
Portland                0
Raleigh/Greensboro      0
Richmond/Norfolk        0
San Francisco           0
Seattle                 0
Tampa                   0
dtype: int64

Unnötige Spalten löschen

In [22]:
df.columns

Index(['date_number', 'date', 'average_price', 'total_volume', '4046', '4225',
       '4770', 'total_bags', 'small_bags', 'large_bags', 'xlarge_bags', 'type',
       'year', 'month_sin', 'month_cos', 'lag_7', 'lag_30', 'moving_avg_30',
       'harvest_indicator', 'geography_encoded', 'latitude', 'longitude',
       'dist_to_california', 'dist_to_mexico', 'region', 'Atlanta',
       'Baltimore/Washington', 'Boston', 'California', 'Hartford/Springfield',
       'Los Angeles', 'Miami/Ft. Lauderdale', 'New York', 'Orlando',
       'Philadelphia', 'Portland', 'Raleigh/Greensboro', 'Richmond/Norfolk',
       'San Francisco', 'Seattle', 'Tampa'],
      dtype='object')

# Spalten löschen

In [23]:
# Entfernen der angegebenen Spalten
df = df.drop(columns=['date','geography_encoded', 'latitude', 'longitude'])

# Ausgabe der ersten Zeilen des Datensatzes zur Überprüfung
print(df.head())

   date_number  average_price  total_volume      4046      4225      4770  \
2            0           1.54       4212.16    238.48   1678.83    372.55
3            0           1.13     182697.97  56293.75  80396.09   9762.41
4            0           2.01       3397.00     58.22   1493.90    772.21
5            0           1.20     221086.46  53316.16  72178.46  39928.01
6            0           1.28      32927.82  17580.96  11685.08      3.15

   total_bags  small_bags  large_bags  xlarge_bags  ...  Miami/Ft. Lauderdale  \
2     1922.30     1570.28      352.02          0.0  ...                     0
3    36245.72    31778.36     4467.36          0.0  ...                     0
4     1072.67      993.94       78.73          0.0  ...                     0
5    55663.83    44040.64    11623.19          0.0  ...                     0
6     3658.63      613.33     3045.30          0.0  ...                     0

   New York  Orlando  Philadelphia  Portland  Raleigh/Greensboro  \
2         0        0             0         0                   0
3         0        0             0         0                   0
4         0        0             0         0                   1
5         0        0             0         0                   1
6         0        0             0         1                   0

   Richmond/Norfolk  San Francisco  Seattle  Tampa
2                 1              0        0      0
3                 1              0        0      0
4                 0              0        0      0
5                 0              0        0      0
6                 0              0        0      0

[5 rows x 37 columns]

In [24]:
# -------------------- WENIGER SPALTEN LÖSCHEN ALS IM 2. DURCHGANG -------------------------

# Entfernen der angegebenen Spalten
df = df.drop(columns=['total_bags','date_number'])

# Ausgabe der ersten Zeilen des Datensatzes zur Überprüfung
print(df.head())

   average_price  total_volume      4046      4225      4770  small_bags  \
2           1.54       4212.16    238.48   1678.83    372.55     1570.28
3           1.13     182697.97  56293.75  80396.09   9762.41    31778.36
4           2.01       3397.00     58.22   1493.90    772.21      993.94
5           1.20     221086.46  53316.16  72178.46  39928.01    44040.64
6           1.28      32927.82  17580.96  11685.08      3.15      613.33

   large_bags  xlarge_bags  type  year  ...  Miami/Ft. Lauderdale  New York  \
2      352.02          0.0     1  2015  ...                     0         0
3     4467.36          0.0     0  2015  ...                     0         0
4       78.73          0.0     1  2015  ...                     0         0
5    11623.19          0.0     0  2015  ...                     0         0
6     3045.30          0.0     1  2015  ...                     0         0

   Orlando  Philadelphia  Portland  Raleigh/Greensboro  Richmond/Norfolk  \
2        0             0         0                   0                 1
3        0             0         0                   0                 1
4        0             0         0                   1                 0
5        0             0         0                   1                 0
6        0             0         1                   0                 0

   San Francisco  Seattle  Tampa
2              0        0      0
3              0        0      0
4              0        0      0
5              0        0      0
6              0        0      0

[5 rows x 35 columns]

In [25]:
df.describe()

,average_price,total_volume,4046,4225,4770,small_bags,large_bags,xlarge_bags,type,year,...,Miami/Ft. Lauderdale,New York,Orlando,Philadelphia,Portland,Raleigh/Greensboro,Richmond/Norfolk,San Francisco,Seattle,Tampa
count,9792.000000,9.792000e+03,9.792000e+03,9.792000e+03,9792.000000,9.792000e+03,9.792000e+03,9792.000000,9792.000000,9792.000000,...,9792.000000,9792.000000,9792.000000,9792.000000,9792.000000,9792.000000,9792.000000,9792.000000,9792.000000,9792.000000
mean,1.470276,5.951879e+05,1.703808e+05,1.920642e+05,11679.888635,1.644586e+05,4.927934e+04,7323.899579,0.500000,2017.460784,...,0.062500,0.062500,0.062500,0.062500,0.062500,0.062500,0.062500,0.062500,0.062500,0.062500
std,0.404028,1.219514e+06,4.418558e+05,3.947694e+05,38117.754919,3.589197e+05,1.459845e+05,39313.439275,0.500026,1.699788,...,0.242074,0.242074,0.242074,0.242074,0.242074,0.242074,0.242074,0.242074,0.242074,0.242074
min,0.530000,8.456000e+01,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000,2015.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1.170000,2.052378e+04,8.383325e+02,4.529765e+03,0.000000,7.845360e+03,1.831975e+02,0.000000,0.000000,2016.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,1.410000,2.169352e+05,1.448774e+04,3.035217e+04,177.895000,5.470730e+04,4.611000e+03,0.000000,0.500000,2017.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,1.730000,6.182481e+05,1.284867e+05,2.019715e+05,3138.980000,1.376183e+05,4.175320e+04,550.805000,1.000000,2019.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,3.250000,1.132468e+07,4.794142e+06,4.097592e+06,442834.000000,4.017035e+06,2.389750e+06,730833.290000,1.000000,2020.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

# 1/total_volume - neue Spalte

In [26]:
# Re-adding the '1/total_volume' column for calculation
df['1/total_volume'] = 1 / df['total_volume']

# Entfernen der 'total_volume'-Spalte
df = df.drop(columns=['total_volume'])

# Homogene Untermengen

In [27]:
# Aufteilen des Datensatzes basierend auf dem Typ und der Region
# Annahme: 'type' ist die Spalte, die angibt, ob es sich um 'organic' (1) oder 'conventional' (0) handelt
# Annahme: 'region' ist die Spalte, die angibt, ob es sich um 'West' (0) oder 'East' (1) handelt

df_organic = df[df['type'] == 1].copy()  # Organic: type == 1
df_conventional = df[df['type'] == 0].copy()  # Conventional: type == 0

df_organic_west = df_organic[df_organic['region'] == 0]
df_organic_east = df_organic[df_organic['region'] == 1]
df_conventional_west = df_conventional[df_conventional['region'] == 0]
df_conventional_east = df_conventional[df_conventional['region'] == 1]

# Train-Test-Split

In [28]:
# Funktion zur Aufteilung in Train und Test für einen gegebenen Datensatz
def split_train_test(df, target_column='average_price', train_year=2020):
    train_df = df[df['year'] < train_year]
    test_df = df[df['year'] >= train_year]
    X_train = train_df.drop(columns=[target_column])
    y_train = train_df[target_column]
    X_test = test_df.drop(columns=[target_column])
    y_test = test_df[target_column]
    return X_train, y_train, X_test, y_test

# Organic West
X_train_organic_west, y_train_organic_west, X_test_organic_west, y_test_organic_west = split_train_test(df_organic_west)
print("Organic West - Train-Daten:", X_train_organic_west.shape, y_train_organic_west.shape)
print("Organic West - Test-Daten:", X_test_organic_west.shape, y_test_organic_west.shape)

# Organic East
X_train_organic_east, y_train_organic_east, X_test_organic_east, y_test_organic_east = split_train_test(df_organic_east)
print("Organic East - Train-Daten:", X_train_organic_east.shape, y_train_organic_east.shape)
print("Organic East - Test-Daten:", X_test_organic_east.shape, y_test_organic_east.shape)

# Conventional West
X_train_conventional_west, y_train_conventional_west, X_test_conventional_west, y_test_conventional_west = split_train_test(df_conventional_west)
print("Conventional West - Train-Daten:", X_train_conventional_west.shape, y_train_conventional_west.shape)
print("Conventional West - Test-Daten:", X_test_conventional_west.shape, y_test_conventional_west.shape)

# Conventional East
X_train_conventional_east, y_train_conventional_east, X_test_conventional_east, y_test_conventional_east = split_train_test(df_conventional_east)
print("Conventional East - Train-Daten:", X_train_conventional_east.shape, y_train_conventional_east.shape)
print("Conventional East - Test-Daten:", X_test_conventional_east.shape, y_test_conventional_east.shape)

Organic West - Train-Daten: (1290, 34) (1290,)
Organic West - Test-Daten: (240, 34) (240,)
Organic East - Train-Daten: (2838, 34) (2838,)
Organic East - Test-Daten: (528, 34) (528,)
Conventional West - Train-Daten: (1290, 34) (1290,)
Conventional West - Test-Daten: (240, 34) (240,)
Conventional East - Train-Daten: (2838, 34) (2838,)
Conventional East - Test-Daten: (528, 34) (528,)

# Scaler

In [29]:
# Import necessary libraries
from sklearn.preprocessing import StandardScaler
import pandas as pd

# Liste der zu skalierenden Spalten
columns_to_scale = ['1/total_volume', '4046', '4225', '4770', 'small_bags', 'large_bags', 'xlarge_bags',
                    'dist_to_california', 'dist_to_mexico', 'lag_7', 'lag_30', 'moving_avg_30']

# Funktion zur Skalierung der Trainings- und Testdaten für einen Datensatz
def scale_data(X_train, X_test, columns):
    scaler = StandardScaler()
    X_train[columns] = scaler.fit_transform(X_train[columns])
    X_test[columns] = scaler.transform(X_test[columns])
    return X_train, X_test

# Skalierung für Organic West
X_train_organic_west, X_test_organic_west = scale_data(X_train_organic_west, X_test_organic_west, columns_to_scale)
print("Organic West - Skalierte Train-Daten:", X_train_organic_west.shape)
print("Organic West - Skalierte Test-Daten:", X_test_organic_west.shape)

# Skalierung für Organic East
X_train_organic_east, X_test_organic_east = scale_data(X_train_organic_east, X_test_organic_east, columns_to_scale)
print("Organic East - Skalierte Train-Daten:", X_train_organic_east.shape)
print("Organic East - Skalierte Test-Daten:", X_test_organic_east.shape)

# Skalierung für Conventional West
X_train_conventional_west, X_test_conventional_west = scale_data(X_train_conventional_west, X_test_conventional_west, columns_to_scale)
print("Conventional West - Skalierte Train-Daten:", X_train_conventional_west.shape)
print("Conventional West - Skalierte Test-Daten:", X_test_conventional_west.shape)

# Skalierung für Conventional East
X_train_conventional_east, X_test_conventional_east = scale_data(X_train_conventional_east, X_test_conventional_east, columns_to_scale)
print("Conventional East - Skalierte Train-Daten:", X_train_conventional_east.shape)
print("Conventional East - Skalierte Test-Daten:", X_test_conventional_east.shape)

Organic West - Skalierte Train-Daten: (1290, 34)
Organic West - Skalierte Test-Daten: (240, 34)
Organic East - Skalierte Train-Daten: (2838, 34)
Organic East - Skalierte Test-Daten: (528, 34)
Conventional West - Skalierte Train-Daten: (1290, 34)
Conventional West - Skalierte Test-Daten: (240, 34)
Conventional East - Skalierte Train-Daten: (2838, 34)
Conventional East - Skalierte Test-Daten: (528, 34)

In [30]:
# Funktion zum Entfernen der angegebenen Spalte aus Trainings- und Testdaten
def drop_columns(X_train, X_test, columns):
    X_train = X_train.drop(columns=columns)
    X_test = X_test.drop(columns=columns)
    return X_train, X_test

# Entfernen der 'year' Spalte für Organic West
X_train_organic_west, X_test_organic_west = drop_columns(X_train_organic_west, X_test_organic_west, ['year'])

# Entfernen der 'year' Spalte für Organic East
X_train_organic_east, X_test_organic_east = drop_columns(X_train_organic_east, X_test_organic_east, ['year'])

# Entfernen der 'year' Spalte für Conventional West
X_train_conventional_west, X_test_conventional_west = drop_columns(X_train_conventional_west, X_test_conventional_west, ['year'])

# Entfernen der 'year' Spalte für Conventional East
X_train_conventional_east, X_test_conventional_east = drop_columns(X_train_conventional_east, X_test_conventional_east, ['year'])

In [32]:
#Output the shapes and first few rows of scaled data for verification
X_train_conventional_east.head()

,4046,4225,4770,small_bags,large_bags,xlarge_bags,type,month_sin,month_cos,lag_7,...,New York,Orlando,Philadelphia,Portland,Raleigh/Greensboro,Richmond/Norfolk,San Francisco,Seattle,Tampa,1/total_volume
3,-0.565320,-0.581699,0.247805,-0.919729,-0.650268,-0.448477,0,0.5,0.866025,-0.789389,...,0,0,0,0,0,1,0,0,0,2.755173
5,-0.586982,-0.608225,2.469498,-0.809078,-0.543757,-0.448477,0,0.5,0.866025,-0.598192,...,0,0,0,0,1,0,0,0,0,1.927383
15,-0.798868,0.110101,-0.314951,-0.549291,-0.511089,-0.448477,0,0.5,0.866025,0.740189,...,0,0,1,0,0,0,0,0,0,0.124263
17,0.412801,-0.717694,-0.465656,-1.026612,-0.228761,-0.448477,0,0.5,0.866025,1.067956,...,0,1,0,0,0,0,0,0,0,1.078563
23,-0.802869,2.799479,-0.333392,0.405897,0.337252,-0.448477,0,0.5,0.866025,1.040642,...,1,0,0,0,0,0,0,0,0,-1.391368

# Datenspeicherung in Pickle

In [33]:
# Import der Pickle-Bibliothek
import pickle

# Funktion zum Speichern von Daten in eine Pickle-Datei
def save_to_pickle(filename, X_train, y_train, X_test, y_test):
    with open(filename, 'wb') as f:
        pickle.dump((X_train, y_train, X_test, y_test), f)
    print(f"Die Daten wurden erfolgreich in die Datei '{filename}' gespeichert.")

# Speichern der Daten für Organic West
save_to_pickle('data/organic_west_data_v3.pkl', X_train_organic_west, y_train_organic_west, X_test_organic_west, y_test_organic_west)

# Speichern der Daten für Organic East
save_to_pickle('data/organic_east_data_v3.pkl', X_train_organic_east, y_train_organic_east, X_test_organic_east, y_test_organic_east)

# Speichern der Daten für Conventional West
save_to_pickle('data/conventional_west_data_v3.pkl', X_train_conventional_west, y_train_conventional_west, X_test_conventional_west, y_test_conventional_west)

# Speichern der Daten für Conventional East
save_to_pickle('data/conventional_east_data_v3.pkl', X_train_conventional_east, y_train_conventional_east, X_test_conventional_east, y_test_conventional_east)

Die Daten wurden erfolgreich in die Datei 'data/organic_west_data_v3.pkl' gespeichert.
Die Daten wurden erfolgreich in die Datei 'data/organic_east_data_v3.pkl' gespeichert.
Die Daten wurden erfolgreich in die Datei 'data/conventional_west_data_v3.pkl' gespeichert.
Die Daten wurden erfolgreich in die Datei 'data/conventional_east_data_v3.pkl' gespeichert.

In [ ]:

# # Laden der gespeicherten Pickle-Datei
# with open('data/train_test_data_v3.pkl', 'rb') as f:
#     X_train, y_train, X_test, y_test = pickle.load(f)

# # Überprüfen der geladenen Daten
# print(X_train.shape, y_train.shape, X_test.shape, y_test.shape)